"""fix: remove unique constraints from all cases except ip

Revision ID: 04ff4f1c94d3
Revises: 7a4d7411a4e6
Create Date: 2023-02-24 12:54:39.141139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04ff4f1c94d3'
down_revision = '7a4d7411a4e6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_names_name_dp', table_name='names')
    op.create_index(op.f('ix_names_name_dp'), 'names', ['name_dp'], unique=False)
    op.drop_index('ix_names_name_rp', table_name='names')
    op.create_index(op.f('ix_names_name_rp'), 'names', ['name_rp'], unique=False)
    op.drop_index('ix_names_name_tp', table_name='names')
    op.create_index(op.f('ix_names_name_tp'), 'names', ['name_tp'], unique=False)
    op.drop_index('ix_names_name_vp', table_name='names')
    op.create_index(op.f('ix_names_name_vp'), 'names', ['name_vp'], unique=False)
    op.drop_index('ix_surnames_surname_dp', table_name='surnames')
    op.create_index(op.f('ix_surnames_surname_dp'), 'surnames', ['surname_dp'], unique=False)
    op.drop_index('ix_surnames_surname_rp', table_name='surnames')
    op.create_index(op.f('ix_surnames_surname_rp'), 'surnames', ['surname_rp'], unique=False)
    op.drop_index('ix_surnames_surname_tp', table_name='surnames')
    op.create_index(op.f('ix_surnames_surname_tp'), 'surnames', ['surname_tp'], unique=False)
    op.drop_index('ix_surnames_surname_vp', table_name='surnames')
    op.create_index(op.f('ix_surnames_surname_vp'), 'surnames', ['surname_vp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_surnames_surname_vp'), table_name='surnames')
    op.create_index('ix_surnames_surname_vp', 'surnames', ['surname_vp'], unique=False)
    op.drop_index(op.f('ix_surnames_surname_tp'), table_name='surnames')
    op.create_index('ix_surnames_surname_tp', 'surnames', ['surname_tp'], unique=False)
    op.drop_index(op.f('ix_surnames_surname_rp'), table_name='surnames')
    op.create_index('ix_surnames_surname_rp', 'surnames', ['surname_rp'], unique=False)
    op.drop_index(op.f('ix_surnames_surname_dp'), table_name='surnames')
    op.create_index('ix_surnames_surname_dp', 'surnames', ['surname_dp'], unique=False)
    op.drop_index(op.f('ix_names_name_vp'), table_name='names')
    op.create_index('ix_names_name_vp', 'names', ['name_vp'], unique=False)
    op.drop_index(op.f('ix_names_name_tp'), table_name='names')
    op.create_index('ix_names_name_tp', 'names', ['name_tp'], unique=False)
    op.drop_index(op.f('ix_names_name_rp'), table_name='names')
    op.create_index('ix_names_name_rp', 'names', ['name_rp'], unique=False)
    op.drop_index(op.f('ix_names_name_dp'), table_name='names')
    op.create_index('ix_names_name_dp', 'names', ['name_dp'], unique=False)
    # ### end Alembic commands ###
