"""feat: cases

Revision ID: 15b31b2b46cf
Revises: 9bad83ca1613
Create Date: 2023-02-23 21:44:47.517255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15b31b2b46cf'
down_revision = '9bad83ca1613'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('names', sa.Column('name_ip', sa.String(), nullable=True))
    op.add_column('names', sa.Column('name_rp', sa.String(), nullable=True))
    op.add_column('names', sa.Column('name_dp', sa.String(), nullable=True))
    op.add_column('names', sa.Column('name_vp', sa.String(), nullable=True))
    op.add_column('names', sa.Column('name_tp', sa.String(), nullable=True))
    op.add_column('names', sa.Column('name_pp', sa.String(), nullable=True))
    op.drop_index('ix_names_name', table_name='names')
    op.create_index(op.f('ix_names_name_dp'), 'names', ['name_dp'], unique=True)
    op.create_index(op.f('ix_names_name_ip'), 'names', ['name_ip'], unique=True)
    op.create_index(op.f('ix_names_name_pp'), 'names', ['name_pp'], unique=True)
    op.create_index(op.f('ix_names_name_rp'), 'names', ['name_rp'], unique=True)
    op.create_index(op.f('ix_names_name_tp'), 'names', ['name_tp'], unique=True)
    op.create_index(op.f('ix_names_name_vp'), 'names', ['name_vp'], unique=True)
    op.drop_column('names', 'name')
    op.add_column('surnames', sa.Column('surname_ip', sa.String(), nullable=True))
    op.add_column('surnames', sa.Column('surname_rp', sa.String(), nullable=True))
    op.add_column('surnames', sa.Column('surname_dp', sa.String(), nullable=True))
    op.add_column('surnames', sa.Column('surname_vp', sa.String(), nullable=True))
    op.add_column('surnames', sa.Column('surname_tp', sa.String(), nullable=True))
    op.add_column('surnames', sa.Column('surname_pp', sa.String(), nullable=True))
    op.drop_index('ix_surnames_surname', table_name='surnames')
    op.create_index(op.f('ix_surnames_surname_dp'), 'surnames', ['surname_dp'], unique=True)
    op.create_index(op.f('ix_surnames_surname_ip'), 'surnames', ['surname_ip'], unique=True)
    op.create_index(op.f('ix_surnames_surname_pp'), 'surnames', ['surname_pp'], unique=True)
    op.create_index(op.f('ix_surnames_surname_rp'), 'surnames', ['surname_rp'], unique=True)
    op.create_index(op.f('ix_surnames_surname_tp'), 'surnames', ['surname_tp'], unique=True)
    op.create_index(op.f('ix_surnames_surname_vp'), 'surnames', ['surname_vp'], unique=True)
    op.drop_column('surnames', 'surname')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surnames', sa.Column('surname', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_surnames_surname_vp'), table_name='surnames')
    op.drop_index(op.f('ix_surnames_surname_tp'), table_name='surnames')
    op.drop_index(op.f('ix_surnames_surname_rp'), table_name='surnames')
    op.drop_index(op.f('ix_surnames_surname_pp'), table_name='surnames')
    op.drop_index(op.f('ix_surnames_surname_ip'), table_name='surnames')
    op.drop_index(op.f('ix_surnames_surname_dp'), table_name='surnames')
    op.create_index('ix_surnames_surname', 'surnames', ['surname'], unique=False)
    op.drop_column('surnames', 'surname_pp')
    op.drop_column('surnames', 'surname_tp')
    op.drop_column('surnames', 'surname_vp')
    op.drop_column('surnames', 'surname_dp')
    op.drop_column('surnames', 'surname_rp')
    op.drop_column('surnames', 'surname_ip')
    op.add_column('names', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_names_name_vp'), table_name='names')
    op.drop_index(op.f('ix_names_name_tp'), table_name='names')
    op.drop_index(op.f('ix_names_name_rp'), table_name='names')
    op.drop_index(op.f('ix_names_name_pp'), table_name='names')
    op.drop_index(op.f('ix_names_name_ip'), table_name='names')
    op.drop_index(op.f('ix_names_name_dp'), table_name='names')
    op.create_index('ix_names_name', 'names', ['name'], unique=False)
    op.drop_column('names', 'name_pp')
    op.drop_column('names', 'name_tp')
    op.drop_column('names', 'name_vp')
    op.drop_column('names', 'name_dp')
    op.drop_column('names', 'name_rp')
    op.drop_column('names', 'name_ip')
    # ### end Alembic commands ###
