"""chore: return indexes

Revision ID: 3a323ccd510b
Revises: 4d87d5385a20
Create Date: 2023-02-25 01:47:46.753389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a323ccd510b'
down_revision = '4d87d5385a20'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_surnames_surname_dp'), 'surnames', ['surname_dp'], unique=False)
    op.create_index(op.f('ix_surnames_surname_pp'), 'surnames', ['surname_pp'], unique=False)
    op.create_index(op.f('ix_surnames_surname_rp'), 'surnames', ['surname_rp'], unique=False)
    op.create_index(op.f('ix_surnames_surname_tp'), 'surnames', ['surname_tp'], unique=False)
    op.create_index(op.f('ix_surnames_surname_vp'), 'surnames', ['surname_vp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_surnames_surname_vp'), table_name='surnames')
    op.drop_index(op.f('ix_surnames_surname_tp'), table_name='surnames')
    op.drop_index(op.f('ix_surnames_surname_rp'), table_name='surnames')
    op.drop_index(op.f('ix_surnames_surname_pp'), table_name='surnames')
    op.drop_index(op.f('ix_surnames_surname_dp'), table_name='surnames')
    # ### end Alembic commands ###
