"""chore: temporarily remove indexes for faster value updating

Revision ID: 4d87d5385a20
Revises: 04ff4f1c94d3
Create Date: 2023-02-25 00:39:53.777506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d87d5385a20'
down_revision = '04ff4f1c94d3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_surnames_surname_dp', table_name='surnames')
    op.drop_index('ix_surnames_surname_pp', table_name='surnames')
    op.drop_index('ix_surnames_surname_rp', table_name='surnames')
    op.drop_index('ix_surnames_surname_tp', table_name='surnames')
    op.drop_index('ix_surnames_surname_vp', table_name='surnames')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_surnames_surname_vp', 'surnames', ['surname_vp'], unique=False)
    op.create_index('ix_surnames_surname_tp', 'surnames', ['surname_tp'], unique=False)
    op.create_index('ix_surnames_surname_rp', 'surnames', ['surname_rp'], unique=False)
    op.create_index('ix_surnames_surname_pp', 'surnames', ['surname_pp'], unique=False)
    op.create_index('ix_surnames_surname_dp', 'surnames', ['surname_dp'], unique=False)
    # ### end Alembic commands ###
