"""feat: subjects

Revision ID: 52da8c471998
Revises: 3a323ccd510b
Create Date: 2023-04-03 22:59:15.077780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52da8c471998'
down_revision = '3a323ccd510b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('lemma', sa.String(), nullable=True),
    sa.Column('acronym', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subjects_acronym'), 'subjects', ['acronym'], unique=False)
    op.create_index(op.f('ix_subjects_lemma'), 'subjects', ['lemma'], unique=False)
    op.create_index(op.f('ix_subjects_subject'), 'subjects', ['subject'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subjects_subject'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_lemma'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_acronym'), table_name='subjects')
    op.drop_table('subjects')
    # ### end Alembic commands ###
