"""fix: remove unique constraint from pp

Revision ID: 7a4d7411a4e6
Revises: 15b31b2b46cf
Create Date: 2023-02-24 12:38:38.662139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a4d7411a4e6'
down_revision = '15b31b2b46cf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_names_name_pp', table_name='names')
    op.create_index(op.f('ix_names_name_pp'), 'names', ['name_pp'], unique=False)
    op.drop_index('ix_surnames_surname_pp', table_name='surnames')
    op.create_index(op.f('ix_surnames_surname_pp'), 'surnames', ['surname_pp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_surnames_surname_pp'), table_name='surnames')
    op.create_index('ix_surnames_surname_pp', 'surnames', ['surname_pp'], unique=False)
    op.drop_index(op.f('ix_names_name_pp'), table_name='names')
    op.create_index('ix_names_name_pp', 'names', ['name_pp'], unique=False)
    # ### end Alembic commands ###
