"""Init revision

Revision ID: 9bad83ca1613
Revises: 
Create Date: 2023-02-23 21:42:54.316299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bad83ca1613'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('names',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('sex', sa.Enum('М', 'Ж', name='ct_names_sex'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_names_name'), 'names', ['name'], unique=True)
    op.create_table('surnames',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('surname', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_surnames_surname'), 'surnames', ['surname'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_surnames_surname'), table_name='surnames')
    op.drop_table('surnames')
    op.drop_index(op.f('ix_names_name'), table_name='names')
    op.drop_table('names')
    # ### end Alembic commands ###
